### ISSUE TITLE
On & Off Delay 

### ISSUE THREAD

**Issue by arkadiush1** [tickez/homebridge-viera#1]
Hello,
A really great plugin. Is it possible to add on and off delay configuration (e. g. 1-3000 ms) to config. json file? My TX-58DX730 needs longer ON/OFF time.
Thank you.
A

**Comment by tickez** [comment]
Hi
Did you check out the homebridge-panasonictv plugin? Your TV should be properly supported by this plugin, I guess. 
This plugin is a really basic version that essentially can only power off the older Viera TVs.
